name: "dc"

# volumes:
#   db-data:

services:
  node:
    # image: app-dc-node:latest
    build:
      context: ./docker/node
      args:
        - UID=1000
        - GID=1000
        - USER_NAME=dev
    user: 1000:1000
    volumes:
      - ./dc:/app
    ports:
      - 5173:5173
      - 3000:3000

  # db:
  #   image: postgres:16
  #   restart: always
  #   shm_size: 128mb
  #   environment:
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres
  #   volumes:
  #     - db-data:/var/lib/postgresql/data/

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: unless-stopped
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=123456
  #   ports:
  #     - 30080:80
